const RATING = [
  `Novice`,
  `Fan`,
  `Movie Buff`,
];

const SHOWING_CARDS_COUNT_ON_START = 5;
const SHOWING_CARDS_COUNT_BY_BUTTON = 5;
const CARDS_COUNT_ADDITIONAL = 2;
const CARDS_COUNT = 15;

export {RATING, CARDS_COUNT, SHOWING_CARDS_COUNT_BY_BUTTON, SHOWING_CARDS_COUNT_ON_START, CARDS_COUNT_ADDITIONAL};
